const express = require('express');
const multer = require('multer');
const pdfParse = require('pdf-parse');
const mammoth = require('mammoth');
const Anthropic = require('@anthropic-ai/sdk');

const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 } });
const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const VALID_TONES = ['professional', 'friendly', 'formal'];
const VALID_LENGTHS = ['short', 'standard', 'detailed'];
const VALID_FOCUSES = ['technical', 'leadership', 'culture'];
const MAX_RESUME_LEN = 30000;
const MAX_JOB_LEN = 15000;

const STYLE_RULES = `
STYLE RULES — follow every one of these without exception:
- Mix short and long sentences. Some sentences should be under 8 words. Some should run longer with natural pauses.
- Use contractions freely: don't, I've, I'm, it's, that's, I'd.
- Vary how paragraphs begin. Do not start more than one paragraph with "I".
- Use active voice throughout.
- Write one intentional sentence fragment for emphasis if it fits. Humans do this.
- No em dashes (—). Replace them with commas, a period, or restructure the sentence.
- No semicolons.
- No bullet points, bold text, or any markdown formatting.
- No lists of three adjectives or skills in a row.
- No parallel structures like "I am skilled in X, proficient in Y, and experienced in Z."
- No "it's not X, it's Y" constructions.
- No trailing -ing phrases that restate what was just said ("emphasizing the significance of...", "highlighting the importance of...").
- No compulsive summaries. Do not use "in conclusion," "overall," or "in summary."
- Do not repeat the company name more than twice. Do not use synonym substitutions for it ("the firm," "the company," "the organization").

BANNED WORDS AND PHRASES — do not use any of these or their close synonyms:
delve, embark, tapestry, realm, landscape, unlock, revolutionize, harness, leverage,
optimize, streamline, foster, pivotal, nuanced, seamless, robust, cutting-edge,
innovative, groundbreaking, remarkable, ever-evolving, game-changer, disruptive,
testament, beacon, synergy, moreover, furthermore, additionally, hence, thus,
it's important to note, it is worth noting, today's fast-paced world,
plays a significant role, serves as a testament, aims to explore, watershed moment,
I am writing to express my interest, I am a highly motivated individual,
I am confident that, Thank you for your consideration, I hope this helps,
utilize, utilizing, elucidate, illuminate, unveil, skyrocket, treasure trove,
showcasing, aligns, impacting, surpassing, dynamic, passionate, results-driven,
I am excited to apply, I am excited about, strong interest in`;

function buildCoverLetterPrompt({ resumeText, jobPosting, tone, length, focus, companyName, positionTitle }) {
  const wordTargets = { short: '220-260', standard: '320-380', detailed: '480-540' };
  const wordTarget = wordTargets[VALID_LENGTHS.includes(length) ? length : 'standard'];

  const toneGuide = {
    professional: 'confident and direct — like a capable person speaking to a peer, not performing eagerness',
    friendly: 'warm and genuine — like someone who is good at their job and also easy to work with',
    formal: 'measured and precise — traditional professional register, no contractions',
  };
  const toneDesc = toneGuide[VALID_TONES.includes(tone) ? tone : 'professional'];

  const focusGuide = {
    technical: 'technical skills, specific tools used, and measurable results',
    leadership: 'ownership, team impact, and moments where this person drove something forward',
    culture: 'why this specific company and role — what connects their background to this team\'s mission',
  };
  const focusDesc = focusGuide[VALID_FOCUSES.includes(focus) ? focus : 'technical'];

  const contextLine = [
    companyName && `The company is ${companyName}.`,
    positionTitle && `The role is ${positionTitle}.`,
  ].filter(Boolean).join(' ');

  return `You are writing a cover letter on behalf of a real job applicant. Output only the letter — no subject line, no commentary, nothing before or after the letter itself.

${contextLine}

The letter must read like it was written by a thoughtful person, not generated by an AI. A hiring manager who reads hundreds of AI cover letters per week should not flag this one.
${STYLE_RULES}

WHAT TO ACTUALLY DO:
- Open with a specific observation or hook — something real from their background or the job posting. Not a declaration of interest.
- Pull concrete details from the resume: actual job titles, real project names, specific numbers or metrics, named technologies.
- Reference 1-2 things from the job posting that actually connect to the candidate's experience — not just mirroring the language back.
- Let the close be confident and brief. No "I look forward to hearing from you at your earliest convenience."

Tone: ${toneDesc}
Target length: ${wordTarget} words
Emphasis: ${focusDesc}

Resume:
${resumeText}

Job Posting:
${jobPosting}

Write the cover letter now.`;
}

router.post('/parse-resume', upload.single('resume'), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });

  const { mimetype, buffer, originalname } = req.file;

  try {
    let text = '';

    if (mimetype === 'application/pdf') {
      const data = await pdfParse(buffer);
      text = data.text;
    } else if (
      mimetype === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
      originalname.endsWith('.docx')
    ) {
      const result = await mammoth.extractRawText({ buffer });
      text = result.value;
    } else if (mimetype === 'text/plain') {
      text = buffer.toString('utf-8');
    } else {
      return res.status(400).json({ error: 'Unsupported file type. Upload PDF, DOCX, or TXT.' });
    }

    if (!text.trim()) return res.status(400).json({ error: 'Could not extract text from file.' });

    res.json({ text: text.trim().slice(0, MAX_RESUME_LEN) });
  } catch (err) {
    console.error('Parse error:', err);
    res.status(400).json({ error: 'Failed to parse resume. Make sure the file is not corrupted.' });
  }
});

router.post('/generate', async (req, res) => {
  const { resumeText, jobPosting, tone, length, focus, companyName, positionTitle } = req.body;

  if (!resumeText || !jobPosting) {
    return res.status(400).json({ error: 'Resume and job posting are required.' });
  }
  if (resumeText.length > MAX_RESUME_LEN) return res.status(400).json({ error: 'Resume text is too long.' });
  if (jobPosting.length > MAX_JOB_LEN) return res.status(400).json({ error: 'Job posting is too long.' });

  const safeCompany = typeof companyName === 'string' ? companyName.slice(0, 100) : '';
  const safePosition = typeof positionTitle === 'string' ? positionTitle.slice(0, 100) : '';

  const prompt = buildCoverLetterPrompt({ resumeText, jobPosting, tone, length, focus, companyName: safeCompany, positionTitle: safePosition });

  try {
    const message = await client.messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    });

    const textBlock = message.content?.[0];
    if (!textBlock || textBlock.type !== 'text' || !textBlock.text) {
      throw new Error('Unexpected response from AI. Please try again.');
    }

    res.json({ letter: textBlock.text.trim() });
  } catch (err) {
    console.error('Claude error:', err);
    const msg = err.status === 429
      ? 'Rate limit reached. Please wait a moment and try again.'
      : err.message || 'Failed to generate cover letter.';
    res.status(500).json({ error: msg });
  }
});

router.post('/rethink-paragraph', async (req, res) => {
  const { paragraph, fullLetter, resumeText, jobPosting, companyName, positionTitle } = req.body;

  if (!paragraph || !fullLetter || !resumeText || !jobPosting) {
    return res.status(400).json({ error: 'Missing required fields.' });
  }

  const safeCompany = typeof companyName === 'string' ? companyName.slice(0, 100) : '';
  const safePosition = typeof positionTitle === 'string' ? positionTitle.slice(0, 100) : '';
  const context = [safeCompany && `Company: ${safeCompany}`, safePosition && `Role: ${safePosition}`].filter(Boolean).join(' | ');

  const prompt = `You are rewriting a single paragraph from a cover letter. Return only the replacement paragraph — nothing else, no explanation.

${context ? `Context: ${context}` : ''}

The paragraph to rewrite:
"""
${paragraph}
"""

The full letter for context (do not rewrite this — use it only as reference):
"""
${fullLetter}
"""

Resume (for specific details to draw from):
"""
${resumeText.slice(0, 8000)}
"""

Job posting (for context):
"""
${jobPosting.slice(0, 4000)}
"""

Write a different version of that paragraph. It must:
- Convey the same general purpose but approach it from a different angle or with different specific details
- Match the tone and register of the rest of the letter
- Sound like a human wrote it — not AI
- Not repeat phrases already used elsewhere in the letter
${STYLE_RULES}

Output only the new paragraph. No quotes, no labels, no explanation.`;

  try {
    const message = await client.messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 512,
      messages: [{ role: 'user', content: prompt }],
    });

    const textBlock = message.content?.[0];
    if (!textBlock || textBlock.type !== 'text' || !textBlock.text) {
      throw new Error('Unexpected response from AI. Please try again.');
    }

    res.json({ paragraph: textBlock.text.trim() });
  } catch (err) {
    console.error('Rethink error:', err);
    const msg = err.status === 429
      ? 'Rate limit reached. Please wait a moment and try again.'
      : err.message || 'Failed to rethink paragraph.';
    res.status(500).json({ error: msg });
  }
});

module.exports = router;
